# Generated by Django 3.2.5 on 2021-07-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('review', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='NA', null=True, upload_to='')),
            ],
            options={
                'db_table': 'Product_Info',
            },
        ),
    ]
